import pyautogui
import time
time.sleep(1)
pyautogui.moveTo(1250,10)
pyautogui.click(button = "left")
time.sleep(1)
pyautogui.moveTo(1320,10)
pyautogui.click(button = "right")
time.sleep(1)
pyautogui.moveTo(1320,20)
pyautogui.click(button = "right")
time.sleep(1)
pyautogui.hotkey('ctrl',"a")
time.sleep(1)
pyautogui.hotkey('ctrl',"c")
time.sleep(1)
pyautogui.hotkey('alt',"F4")
time.sleep(1)
pyautogui.moveTo(1320,150)
time.sleep(1)
pyautogui.doubleClick(button = "left")
time.sleep(1)
pyautogui.hotkey('ctrl',"v")
time.sleep(1)
pyautogui.hotkey('alt',"F4")
pyautogui.moveTo(620,390)
pyautogui.click(button = "left")
